### ISSUE TITLE
fix: 배포를 위한 타입 오류 수정

### ISSUE THREAD

**Issue by HyungJu** [goormthon-Univ/2024_BEOTKKOTTHON_TEAM_4_FE#7]
### ⚠️ Issue
- `next build`로 빌드를 할 때 타입 오류가 발생하면 빌드가 실패하는 문제가 있습니다 ..!!
- 그래서 지금은 next.config.mjs를 강제로 오버라이딩해서 배포를 해뒀는데, 이건 분명 좋은 방법이 아니기에 .. 타입 에러 수정을 부탁드립니다 !

**Comment by osohyun0224** [comment]
형주님 확인했습니다! 감사합니다 🙆🏻‍♀️

**Comment by minjeoong** [comment]
확인했습니다! 감사합니다 !!
